[package]
name = "rs-floats2tdigest"
version = "0.1.0"
edition = "2024"

description = "CLI for computing t-digest from floats."
license = "Apache-2.0"
repository = "https://github.com/takanoriyanagitani/rs-floats2tdigest"
homepage = "https://github.com/takanoriyanagitani/rs-floats2tdigest"
documentation = "https://docs.rs/rs-floats2tdigest/latest"
keywords = ["tdigest", "float", "wasi", "convert"]

exclude = [
  "floats2tdigest.wasm",
]

[profile.release-wasi]
inherits = "release"
lto = true
strip = true
opt-level = 's'
codegen-units = 1

[[bin]]
name = "floats2tdigest"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "forbid"
expect_used = "forbid"
panic = "forbid"

[dependencies.tdigest]
version = "1.0.1"
default-features = false
features = [
  "std",
  "serde",
]

[dependencies.serde_json]
version = "1"
default-features = false
features = [
  "std",
]
